language: python
python:
    - "3.6"
install:
    - pip install coveralls
    - pip install -r requirements.txt
script:
    # run tests with coverage
    - coverage run --source=btclib setup.py test
after_success:
    # upload reports to coveralls.io
    - coveralls
